title: "Kiran"
description: "Personal website"
theme: minima
author: Kiran
markdown: kramdown
permalink: pretty
# Navigation menu
nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
  - name: "Technical Notes"
    link: "/notes/Indirect_non_linear_constrains"
  - name: "Contact"
    link: "/contact"
  

