title: "Kiran M Aralikatti"
description: "Personal website"
theme: minima
author: Kiran M A
markdown: kramdown
permalink: pretty
# Navigation menu
nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
  - name: "Technical Notes"
    link: "/notes/Indirect_non_linear_constrains"
  - name: "Contact"
    link: "/contact"

collections:
  notes:
    output: true
    permalink: /notes/:name/
    
defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note


