title: "Kiran M Aralikatti"
description: "Trajectory Optimization | GNC | Optimal Control | Aerospace Systems"
url: "https://kirancoder.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  math_engine: mathjax
